# Generated by Django 3.1.4 on 2021-01-01 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210102_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='lesson_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='Коментарий к уроку'),
        ),
    ]
